language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - cat /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get install --force-yes -qq p7zip openjdk-7-jdk ant lib32z1-dev lib32stdc++6
    - sudo update-alternatives --display java
    - sudo update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
    - sh -e /etc/init.d/xvfb start
script:
    - export WORKDIR=$PWD
    - echo $PWD
    - export PATH=$PWD/bin:$PATH
    - ./env/qt-5.5.1-android-19
    - cat qt-5.5.1-android-19.env
    - source qt-5.5.1-android-19.env
    - find $ANDROID_SDK_ROOT/build-tools
    - cat -n $ANDROID_SDK_ROOT/tools/ant/build.xml
    - $ANDROID_SDK_ROOT/build-tools/22.0.1/aidl
    - which qmake
    - git clone https://github.com/benlau/quickandroid.git
    - cd quickandroid/examples/quickandroidexample
    - qmake
    - make install INSTALL_ROOT=$WORKDIR/build
    - androiddeployqt --output $WORKDIR/build
