language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - cat /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get install --force-yes -qq p7zip openjdk-7-jsdk
    - sh -e /etc/init.d/xvfb start
script:
    - export WORKDIR=$PWD
    - echo $PWD
    - export PATH=$PWD/bin:$PATH
    - ./env/qt-5.5.1-android-19
    - source qt-5.5.1-android-19.env
    - which qmake
    - git clone https://github.com/benlau/quickandroid.git
    - cd quickandroid/examples/quickandroidexample
    - qmake
    - make install INSTALL_ROOT=$WORKDIR/build
    - androiddeployqt --output $WORKDIR/build
